export const people = [
    {
        id: 1,
        name: "Leanne Graham",
        profile: "https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        email: "rahul@april.biz",
        contact: "1-770-736-8031 x56442",
        socialId: "http://hildegard.org",
        like: 0,
    },
    {
        id: 2,
        profile: "https://avatars.dicebear.com/v2/avataaars/Antonette.svg?options[mood][]=happy",
        name: "Ervin Howell",
        email: "Shaniana@melissa.tv",
        contact: "010-692-6593 x09125",
        socialId: "http://anastasia.net",
        like: 0,
    },
    {
        id: 3,
        profile: "https://avatars.dicebear.com/v2/avataaars/Samantha.svg?options[mood][]=happy",
        name: "Clementine Bauch",
        email: "Nathan@yesenia.net",
        contact: "1-463-123-4447",
        socialId: "http://ramiro.info",
        like: 0,
    },
    {
        id: 4,
        profile: "https://avatars.dicebear.com/v2/avataaars/Karianne.svg?options[mood][]=happy",
        name: "Patricia Lebsack",
        email: "Julianne.OConner@kory.org",
        contact: "493-170-9623 x156",
        socialId: "http://kale.biz",
        like: 0,
    },
    {
        id: 5,
        profile: "https://avatars.dicebear.com/v2/avataaars/Kamren.svg?options[mood][]=happy",
        name: "Chelsey Dietrich",
        email: "Lucio_Hettinger@annie.ca",
        contact: "(254)954-1289",
        socialId: "http://demarco.info",
        like: 0,
    },
    {
        id: 6,
        profile: "https://avatars.dicebear.com/v2/avataaars/Leopoldo_Corkery.svg?options[mood][]=happy",
        name: "Mrs. Dennis Schulist",
        email: "Karley_Dach@jasper.info",
        contact: "1-477-935-8478 x6430",
        socialId: "http://ola.org",
        like: 0,
    },
    {
        id: 7,
        profile: "https://avatars.dicebear.com/v2/avataaars/Elwyn.Skiles.svg?options[mood][]=happy",
        name: "Kurtis Weissnat",
        email: "Telly.Hoeger@billy.biz",
        contact: "210.067.6132",
        socialId: "http://elvis.io",
        like: 0,
    },
    {
        id: 8,
        profile: "https://avatars.dicebear.com/v2/avataaars/Maxime_Nienow.svg?options[mood][]=happy",
        name: "Nicholas Runolfsdottir V",
        email: "Sherwood@rosamond.me",
        contact: "586.493.6943 x140",
        socialId: "http://jacynthe.com",
        like: 0,
    },
    {
        id: 9,
        profile: "https://avatars.dicebear.com/v2/avataaars/Delphine.svg?options[mood][]=happy",
        name: "Glenna Reichert",
        email: "Chaim_McDermott@dana.io",
        contact: "(775)976-6794 x41206",
        socialId: "http://conrad.com",
        like: 0,
    },
    {
        id: 10,
        profile: "https://avatars.dicebear.com/v2/avataaars/Moriah.Stanton.svg?options[mood][]=happy",
        name: "Clementina DuBuque",
        email: "Rey.Padberg@karina.biz",
        contact: "024-648-3804",
        socialId: "http://ambrose.net",
        like: 0,
    },        
  ];